version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.26.0
    - 5.26.2
    - 5.34.0  
  assignees:
  - MaxAake
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - MaxAake
